name: build
on: push

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/build-push-action@v6
        with:
          build-args: NODE_VERSION=18.20.4
